{
  results: [
    {
      business_status: 'OPERATIONAL',
      formatted_address: '63 Burelli St, Wollongong NSW 2500, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: 'd09b4d19276a5613adcc2772ecb221c690545397',
      name: 'Woolworths Wollongong',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJdeiUZa8ZE2sRLBJ4s8KNdsw',
      plus_code: [Object],
      price_level: 1,
      rating: 4.1,
      reference: 'ChIJdeiUZa8ZE2sRLBJ4s8KNdsw',
      types: [Array],
      user_ratings_total: 1022
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '19 Princes Hwy, Figtree NSW 2525, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: 'e059fd1fe614788863213e827dffc37468eef8d2',
      name: 'Woolworths Figtree',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJo5fs6fUZE2sRg26DreiZZoE',
      plus_code: [Object],
      price_level: 1,
      rating: 3.9,
      reference: 'ChIJo5fs6fUZE2sRg26DreiZZoE',
      types: [Array],
      user_ratings_total: 238
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '66 Princes Hwy, Fairy Meadow NSW 2519, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: 'a17ce31113f01ad44b192d84da65ba5b811980a4',
      name: 'Woolworths Fairy Meadow',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJS3KX_ToZE2sRdH1FOMngNeM',
      plus_code: [Object],
      price_level: 1,
      rating: 4.2,
      reference: 'ChIJS3KX_ToZE2sRdH1FOMngNeM',
      types: [Array],
      user_ratings_total: 567
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '4-8 Tannery St, Unanderra NSW 2526, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: '7edd2c111d311d36fec05068b58dae8a5149d737',
      name: 'Woolworths Unanderra',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJ_XsdY6MQE2sRFhDBz47-yGw',
      plus_code: [Object],
      price_level: 1,
      rating: 4.1,
      reference: 'ChIJ_XsdY6MQE2sRFhDBz47-yGw',
      types: [Array],
      user_ratings_total: 514
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: 'Stockland Shopping Centre, 270 Princes Hwy, Corrimal NSW 2518, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: '10e30586b94deeb2816164a05d8b428a40339c91',
      name: 'Woolworths Corrimal',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJE5sp7dEeE2sRn0GIF7sP5dE',
      plus_code: [Object],
      price_level: 1,
      rating: 4.1,
      reference: 'ChIJE5sp7dEeE2sRn0GIF7sP5dE',
      types: [Array],
      user_ratings_total: 240
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '425 Crown St, Wollongong NSW 2500, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/gas_station-71.png',
      id: 'd57c00dac5c196cf3ffc4c28262a57beedd39268',
      name: 'Caltex Woolworths Wollongong',
      opening_hours: [Object],
      place_id: 'ChIJwTHzYJcZE2sRNYldipzG8ps',
      plus_code: [Object],
      rating: 3.9,
      reference: 'ChIJwTHzYJcZE2sRNYldipzG8ps',
      types: [Array],
      user_ratings_total: 70
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '75-87 Princes Hwy, Dapto NSW 2530, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: '47aeb701049b6c10e30a27256568fe30aad44f00',
      name: 'Woolworths',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJA0Wf7c4RE2sRTNRHh-SC70k',
      plus_code: [Object],
      price_level: 1,
      rating: 4,
      reference: 'ChIJA0Wf7c4RE2sRTNRHh-SC70k',
      types: [Array],
      user_ratings_total: 270
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '5-9 Molloy St, Bulli NSW 2516, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: 'b68692046ba67760a241a083920d030a91b2369a',
      name: 'Woolworths Bulli',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJY8dnJqwfE2sRJy4AHAVzXwY',
      plus_code: [Object],
      price_level: 1,
      rating: 4.1,
      reference: 'ChIJY8dnJqwfE2sRJy4AHAVzXwY',
      types: [Array],
      user_ratings_total: 560
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: 'Grove Shopping Centre, 29-30 Shellharbour Rd, Warilla NSW 2528, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: '0457b6b2246747df4cdcf4c8c96de6b56111d8e1',
      name: 'Woolworths Warilla',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJF0y0qQkUE2sRHHg1gz50Pdo',
      plus_code: [Object],
      price_level: 1,
      rating: 4.1,
      reference: 'ChIJF0y0qQkUE2sRHHg1gz50Pdo',
      types: [Array],
      user_ratings_total: 263
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: 'Stoney Range Centre, New Lake Entrance Rd, Shellharbour NSW 2529, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: '034b9180fa01bcff2a048c5d1a5395cfd25e9b41',
      name: 'Woolworths',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJFRXQwwkTE2sRiCA5OnQjDQ4',
      plus_code: [Object],
      price_level: 1,
      rating: 4.1,
      reference: 'ChIJFRXQwwkTE2sRiCA5OnQjDQ4',
      types: [Array],
      user_ratings_total: 438
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '211 Lake Entrance Rd, Shellharbour NSW 2529, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: '1109de4be632df9000d83f79ca389ca8137c0ee1',
      name: 'Woolworths Shellharbour',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJ73L61aETE2sRXVewF0YvFQA',
      plus_code: [Object],
      price_level: 1,
      rating: 4.2,
      reference: 'ChIJ73L61aETE2sRXVewF0YvFQA',
      types: [Array],
      user_ratings_total: 264
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '2527/1 Russell St, Albion Park NSW 2527, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: 'e4c6acf27ce6602488321a26cebe563230fc6b0b',
      name: 'Woolworths Albion Park',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJB9-PJKISE2sRReHBqUZqv5o',
      plus_code: [Object],
      price_level: 1,
      rating: 3.8,
      reference: 'ChIJB9-PJKISE2sRReHBqUZqv5o',
      types: [Array],
      user_ratings_total: 423
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '100 Cove Blvd, Shell Cove NSW 2529, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: '9481c825cca9a2fdb4c071b2d2ff04749cf5fae8',
      name: 'Woolworths Shell Cove',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJkS4Qk1QVE2sREi8FZf8vVLM',
      plus_code: [Object],
      price_level: 1,
      rating: 4.4,
      reference: 'ChIJkS4Qk1QVE2sREi8FZf8vVLM',
      types: [Array],
      user_ratings_total: 252
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: 'Wollongong NSW 2500, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
      id: '9d302574a2591f2c281c33898a035a29ff6c71d4',
      name: 'Return and Earn (Woolworths Wollongong)',
      opening_hours: [Object],
      place_id: 'ChIJHVo8r8UZE2sRUGAxc-5wQvM',
      plus_code: [Object],
      rating: 3.7,
      reference: 'ChIJHVo8r8UZE2sRUGAxc-5wQvM',
      types: [Array],
      user_ratings_total: 3
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '63 Burelli St, Wollongong NSW 2500, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png',
      id: '7ace08d1e40f9e79330163363e929b8477039bf2',
      name: 'Secure Parking - Woolworths Wollongong',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJPYJPZK8ZE2sRoiL4P4ur2Rk',
      plus_code: [Object],
      rating: 2.8,
      reference: 'ChIJPYJPZK8ZE2sRoiL4P4ur2Rk',
      types: [Array],
      user_ratings_total: 6
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '117 Remembrance Driveway, Tahmoor NSW 2573, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: '24759334b8621d6cf8fa3a80b341e358809e354a',
      name: 'Woolworths Tahmoor',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJIaBgzeX_EmsRIRLOoxtj6oM',
      plus_code: [Object],
      price_level: 1,
      rating: 3.9,
      reference: 'ChIJIaBgzeX_EmsRIRLOoxtj6oM',
      types: [Array],
      user_ratings_total: 301
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '47 Princes Hwy, Fairy Meadow NSW 2519, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/gas_station-71.png',
      id: 'f062257558600fe0c071f018d742df541bfdf42a',
      name: 'Caltex Woolworths Fairy Meadow',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJh4t7fzwZE2sR8eN2uSgC878',
      plus_code: [Object],
      rating: 3.8,
      reference: 'ChIJh4t7fzwZE2sR8eN2uSgC878',
      types: [Array],
      user_ratings_total: 35
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: 'Princes Hwy, Unanderra NSW 2526, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/gas_station-71.png',
      id: '7cbb312c5a88e7863593dae61dccd47b43d2f144',
      name: 'Caltex Woolworths Unanderra',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJFxYmXaQQE2sRzmpsshXv9j0',
      plus_code: [Object],
      rating: 3.6,
      reference: 'ChIJFxYmXaQQE2sRzmpsshXv9j0',
      types: [Array],
      user_ratings_total: 32
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '200 Crown St, Wollongong NSW 2500, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      id: '6d958458bf6e77ad8de08107a733eba19c02fd35',
      name: 'Coles Wollongong Central',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJ6dp51KUZE2sR2zQvXwG6eIA',
      plus_code: [Object],
      rating: 4.2,
      reference: 'ChIJ6dp51KUZE2sR2zQvXwG6eIA',
      types: [Array],
      user_ratings_total: 444
    },
    {
      business_status: 'OPERATIONAL',
      formatted_address: '275 Princes Hwy, Corrimal NSW 2518, Australia',
      geometry: [Object],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/gas_station-71.png',
      id: 'd823cb9ae1a625f859650d174da2d924939696ae',
      name: 'Caltex Woolworths Corrimal',
      opening_hours: [Object],
      photos: [Array],
      place_id: 'ChIJf4vrBNIeE2sRf_i1MmUSZU8',
      plus_code: [Object],
      rating: 4.1,
      reference: 'ChIJf4vrBNIeE2sRf_i1MmUSZU8',
      types: [Array],
      user_ratings_total: 29
    }
  ];
}
